webapps/root/amsamembership/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$',  RedirectView.as_view(url='register/', permanent=False), name='index'),
	url(r'^register/', include('core.urls', namespace="core")),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG == True:
    urlpatterns += staticfiles_urlpatterns()

webapps/root/core/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submitRegistration/$', views.submitRegistration, name='submitRegistration'),
    url(r'^registration/$', views.registration, name='registration'),
    url(r'^confirmEmail/(?P<externalId>\w+)/(?P<id>\w+)/$', views.confirmEmail, name='confirmEmail'),
]

webapps/root/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class University(models.Model):
	school_name = models.CharField(max_length=100)
	school_domain_name = models.CharField(max_length=100, unique=True)
	approved = models.BooleanField(default=False)

# Create your models here.
class Member(models.Model):
	last_name = models.CharField(max_length=100)
	first_name = models.CharField(max_length=100)
	date_of_birth = models.DateField()
	address1 = models.CharField(max_length=50)
	address2 = models.CharField(max_length=50)
	city = models.CharField(max_length=50)
	state = models.CharField(max_length=50)
	zip_code = models.CharField(max_length=10)
	phone_number = models.CharField(max_length=20)
	personal_email_address = models.CharField(max_length=250, unique=True)
	facebook_link = models.CharField(max_length=250)
	linked_in_link = models.CharField(max_length=250, null=True)
	# PENDING means student filled out the application but not confirmed the amil
	PENDING = 'PE'
	ACCEPTED = 'AC'
	REJECTED = 'RE'
	# HOLDING means the student approved the email but the student is not accepted nor rejected
	HOLDING = 'HO'
	ACCEPTANCE_STATUS_CHOICES = (
		(PENDING, 'Pending'),
		(ACCEPTED, 'Accepted'),
		(REJECTED, 'Rejected'),
		(HOLDING, 'Holding'),
	)
	acceptance_status = models.CharField(
		max_length =2,
    	choices = ACCEPTANCE_STATUS_CHOICES,
    	default = PENDING,
	)
	external_id = models.CharField(max_length=100, unique=True)
	school_name = models.CharField(max_length=100, null=True)

	def __str__( self ):
		return "{0} {1} ({2})".format(self.first_name, self.last_name, self.personal_email_address)

class MemberUniversity(models.Model):
	member = models.ForeignKey(Member)
	university_assigned = models.ForeignKey(University, null=True)
	school_email_address = models.CharField(max_length=250, unique=True)
	BACHELOR = 'BA'
	MASTER = 'MA'
	DOCTOR = 'DR'
	SCHOOL_DEGREE_CHOICES = (
    	(BACHELOR, 'Bachelor\'s'),
		(MASTER, 'Master\'s'),
		(DOCTOR, 'Doctoral'),
	)
	degree_level = models.CharField(
		max_length=2,
    	choices=SCHOOL_DEGREE_CHOICES)
	graduation_year = models.IntegerField()
	major = models.CharField(max_length=250)
	second_major = models.CharField(max_length=250, null=True)

webapps/root/core/views.py
from django.shortcuts import render
from django.db import transaction
from models import *
from dateHelper import *
import uuid
from emailUtils import *
import re

def index(request):
	context = {}
	return render(request, 'core/index.html', context)

def registration(request):
	schoolEmail= "{}.edu".format(request.GET['schoolEmailPrefix'])
	context = {"schoolEmail": schoolEmail}
	domainName = re.search("@[\w.]+", schoolEmail).group()[1:]
	uni = loadUniversityIfExists(domainName)
	if uni != None:
		context['university'] = uni
	context.update(getDateTimeContext())
	context['degreeLevels'] = MemberUniversity.SCHOOL_DEGREE_CHOICES
	return render(request, 'core/registration.html', context)

@transaction.atomic
def submitRegistration(request):
	firstName = request.POST['firstName']
	externalId = uuid.uuid4().hex
	schoolEmail = request.POST['schoolEmail']
	schoolDomainName = retrieveDomain(schoolEmail)
	university = loadUniversityIfExists(schoolDomainName)
	if university != None:
		schoolName = university.school_name
	else:
		schoolName = request.POST['schoolName']
		university = University(
			school_name = schoolName,
			school_domain_name = schoolDomainName)
		university.save()
		## TODO: send out an emailt to approve university
	newApplicant = Member(first_name = request.POST['firstName'],	
						  last_name = request.POST['lastName'],
						  date_of_birth = datetime.date(
						  	year=int(request.POST['birthYear']), 
						  	month=int(request.POST['birthMonth']),
						  	day=int(request.POST['birthDay'])),
						  address1 = request.POST['address1'],
						  address2 = request.POST['address2'],
						  city = request.POST['city'],	
						  state = request.POST['state'],
						  zip_code = request.POST['zip'],
						  phone_number = request.POST['phoneNumber'],
						  personal_email_address = request.POST['personalEmail'],
						  facebook_link = request.POST['facebookLink'],
						  linked_in_link = request.POST['linkedInLink'],
						  external_id = externalId,
						  school_name = schoolName)
	newApplicant.save()
	memberUni = MemberUniversity(
			member = newApplicant,
			university_assigned = university if university != None else None,
			school_email_address = schoolEmail,
			degree_level = request.POST['degreeLevel'],
			graduation_year = int(request.POST['graduationYear']),
			major = request.POST['major'],
			second_major = request.POST['secondMajor'])
	memberUni.save()
	redirect_url = url = request.build_absolute_uri(reverse(
		'core:confirmEmail', 
		kwargs={'externalId': externalId, 'id' : newApplicant.id}))
	send_email_confirmation_mail(
		firstName,
		schoolEmail,
		redirect_url)

	context={'firstName' : firstName, 'schoolEmail': schoolEmail}
	return render(request, 'core/submitRegistration.html', context)


def confirmEmail(request, externalId, id):
	member = Member.objects.get(id=id)
	confirmed = (member.external_id == externalId)

	if (confirmed and member != None):
		uniMember = MemberUniversity.objects.get(member=member)
		member.acceptance_status = Member.ACCEPTED if uniMember.university_assigned.approved else Member.HOLDING
		member.save()
		isAccepted = (member.acceptance_status==Member.ACCEPTED)
		if isAccepted:
			send_acceptance_mail(member.first_name, uniMember.school_email_address)
		else:
			send_pending_mail(member.first_name, uniMember.school_email_address)
		return render(request, 'core/emailConfirmed.html', {'isAccepted':isAccepted})
	else:
		#handle error
		return render(request, 'core/emailConfirmed.html', {'isAccepted':false})
# Helper
def loadOrCreateUniversity(domainName, schoolName):
	existing = loadUniversityIfExists(domainName)
	if existing == None:
		uni = University(school_name = schoolName, school_domain_name = domainName)
		uni.save()
		return uni
	else:
		return existing

# Helper
def loadUniversityIfExists(domainName):
	universities = University.objects.filter(school_domain_name=domainName)
	if len(universities) > 0:
		return universities[0]
	else:
		return None
# Helper
def retrieveDomain(schoolEmail):
	return re.search("@[\w.]+", schoolEmail).group()[1:]

webapps/root/core/templates/core/index.html
{% extends "base.html" %}

{% block body %}

<div class="jumbotron jumbotron-fluid">
<div class="container ">
  <h1 class="display-3" id="hero-title">Where Friendship Begins</h1>
  <p class="lead">"АМЕРИК ДАХЬ МОНГОЛ ОЮУТНЫ ХОЛБОО” төрийн бус байгууллагын зорилго нь дэлхий дахин дахь Монголын шилдэг оюутан, төгсөгчдийг хамарсан сүлжээ, тэдгээрийн мэдээллийн санг бий болгож, Монгол улс болон олон улсад боловсрол, эдийн засаг болон сайн санааны үйлс зохион байгуулж оролцоход оршино.
  </p>
  <form action="{% url 'core:registration' %}" method="get">
  <hr class="my-4">
  <p>Их сургуулийн и-мэйл хаяг</p>
  <div class="row">
    <div class="col-4 input-group">
      <input type="text" class="form-control form-control-lg right-text" name="schoolEmailPrefix" placeholder="@mycollege" aria-describedby="basic-addon2">
       <span class="input-group-addon" id="basic-addon2">.edu</span>
    </div>
    <div class="col-2">
       <input class="btn btn-primary btn-lg" type="submit" value="эхэлцгээе">
    </div>
  </div>
  </form>
</div>
</div>
{% endblock %}

webapps/root/core/templates/core/registration.html
{% extends "registrationBorder.html" %}

{% block content %}

<form action="{% url 'core:submitRegistration' %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="schoolEmail" value="{{schoolEmail}}">
  <div class="container">
  	<div class="row">
      <div class="col-12">
        <div class="row top30"> <div class="col">Нэр </div></div>
        <div class="row top5">
          <div class="col-6">
            <input type="text" class="form-control" name="firstName" placeholder="Өөрийн" required/>
          </div>
          <div class="col-6">
            <input type="text" class="form-control" name="lastName" placeholder="Эцэг/эх нэр" required/>
          </div>
        </div>
        <div class="row top30"> <div class="col">Төрсөн өдөр </div></div>
        <div class="row top5">
            <div class="col-4">
              <select class="form-control" name="birthDay" required/>
              <option value="" disabled selected> Өдөр</option>
              {% for day in days %}
                <option value="{{day}}">{{day}}</option>
              {% endfor %}
              </select>
            </div>
            <div class="col-4">
              <select class="form-control" name="birthMonth" required/>
              <option value="" disabled selected>Сар</option>
              {% for month in months %}
                <option value="{{month}}">{{month}}</option>
              {% endfor %}
              </select>
            </div>
            <div class="col-4">
              <select class="form-control" name="birthYear" required/>
              <option value="" disabled selected>Жил</option>
              {% for year in possibleYearsToBorn %}
                <option value="{{year}}">{{year}}</option>
              {% endfor %}
              </select>
            </div>
        </div>
        <div class="row top30"> <div class="col">Хаяг</div></div>
        <div class="row top5">
          <div class="col-12">
            <input type="text" class="form-control" name="address1" placeholder="Хаяг 1 (123 Main Street)" required/>
          </div>
        </div>

        <div class="row top10">
          <div class="col-12">
            <input type="text" class="form-control" name="address2" placeholder="Хаяг 2 (Apt # 123)" required/>
          </div>
        </div>

        <div class="row top10">
          <div class="col-7">
            <input type="text" class="form-control" name="city" placeholder="Хот" required/>
          </div>
          <div class="col-3">
            {% include "core/stateSelectionDropdown.html" %}
          </div>
          <div class="col-2">
            <input type="text" class="form-control" name="zip" placeholder="Zip Код" required/>
          </div>
        </div>

        <div class="row top30"> <div class="col">Холбоо барих</div></div>
        <div class="row top10">
          <div class="col-6">
            <input type="text" class="form-control" name="phoneNumber" placeholder="Утасны дугаар" required/>
          </div>
          <div class="col-6">
            <input type="text" class="form-control" name="personalEmail" placeholder="Хувийн и-мэйл хаяг" required>
          </div>
        </div>

        <div class="row top30"> <div class="col">Сургуулийн тухай</div></div>
        <div class="row top15">
          <div class="col-8">
            <input type="text" class="form-control" name="schoolName" 
            placeholder="{%if not university%}Одоогийн хамрагдаж буй их сургууль (бүтнээр){%endif%}" {%if university%}value="{{university.school_name}}"{%endif%}  {%if university%}disabled{%endif%} required/>
          </div>
          <div class="col-4">
              <select class="form-control" name="graduationYear" required>
              <option value="" disabled selected>Төгсөх Жил</option>
              {% for year in possibleYearsToGraduate %}
                <option value="{{year}}">{{year}}</option>
              {% endfor %}
              </select>
          </div>
        </div>

        <div class="row top15">
          <div class="col-8">
            <input type="text" class="form-control" name="major" placeholder="Суралцаж буй мэргэжил" required/>
          </div>
          <div class="col-4">
              <select class="form-control" name="degreeLevel" required>
              <option value="" disabled selected>Горилж буй эрдмийн цол</option>
              {% for degreeLevel in degreeLevels %}
                <option value="{{degreeLevel.0}}">{{degreeLevel.1}}</option>
              {% endfor %}
              </select>
            </div>
        </div>

        <div class="row top15">
          <div class="col-12">
            <input type="text" class="form-control" name="secondMajor" placeholder="Давхар суралцаж буй мэргэжил (хэрвээ байгаа бол)"/>
          </div>
        </div>

        <div class="row top30"> <div class="col">Олон нийтийн сүлжээ</div></div>
        <div class="row top10">
          <div class="col-6">
            <input type="text" class="form-control" name="facebookLink" placeholder="Facebook link" required/>
          </div>
          <div class="col-6">
            <input type="text" class="form-control" name="linkedInLink" placeholder="LinkedIn link" required/>
          </div>
        </div>
        <div class="row top30"> 
          <div class="col"><input class="btn btn-primary btn-lg" type="submit" value="Бүртгүүлэх" /></div>
        </div>
      </div>
    </div>
  </div>
  
</form>

{% endblock %}

webapps/root/templates/core/_footer.html
<div class="footer">
<div class="upperFooter">
	<div class="container">
		<div class="row">
		<div class="right col-md-3 col-sm-6 col-xs-12 offset-md-9 offset-sm-6">
			<h4> Холбогдоx Мэдээлэл </h4>
				
                    <p> Асуулт байвал <a href="https://www.facebook.com/oyutniikholboo/" style="opacity:1.0;color:#00aeef;"> Facebook</a>-ээр болон amsa.amox@gmail.com хаягаар бидэнтэй холбогдоно у.</p>
               
        </div>
		</div>
	</div>
</div>
<div class="lowerFooter" 
	style="height: 50px; background-color:#223038;text-align: center;font-size: 13px;color:rgba(255, 255, 255, 0.3); padding: 15px;">
	 © AMSA/АМОX 2017 
</div>
</div>

webapps/root/templates/core/acceptanceLetter.html
{% extends "core/emailLetterBase.html" %}
{% block body %}
<p>Эрхэм {{firstName}} танд энэ өдрийн мэндийг дэвшүүлэе.</p>

<p>Америк дахь Монгол Оюутны Холбоонд гишүүнээр элсэн орох өргөдөл явуулсан таньд баярлалаа. АМОХ-ны гишүүн болсон танд баяр хүргэе. Холбооны гишүүн болсноор та АМОХ-ны <a href="https://www.facebook.com/groups/amsamembers/">Facebook группд</a> орж бусад гишүүдтэй холбогдох ба холбооноос зохион байгуулагдах үйл ажиллагаанд оролцох эрхтэй болж байгаа юм. </p>

<p>Та доорх линкээр орж Facebook группд нэгдэнэ үү. </p>

<p>https://www.facebook.com/groups/amsamembers/</p>

<p>Хэрэв танд АМОХ-ны үйл ажиллагааны талаар лавлах асуулт эсвэл хуваалцах санал бодол байвал amsa.amox@gmail.com хаягаар бидэнтэй холбогдоно уу. </p>

<p>Манай холбооны гэр бүлд тавтай морил.</p>

<p>Хүндэтгэсэн,</p>
<p>АМОХ Төлөөлөн Удирдах Зөвлөл.</p>
{% endblock %}

webapps/root/templates/core/accepted.html
Accepted!

webapps/root/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static '/core/main.css' %}">

<link rel="shortcut icon" type="image/x-icon" href="http://amsa.mn/wp-content/uploads/2012/02/iconfile.png"/>
<title>
    AMSA | Элсэх
 </title>
</head>
<body>
	<div id="container">
		{% block body %}{% endblock %}
	</div>
</body>

webapps/root/templates/core/confirmEmailMailTemplate.html
{% extends "core/emailLetterBase.html" %}
{% block body %}
<h4> Confirm your email address</h1>
<br/><br/>
<p class="callout">Имэйл хаяг баталгаажуулахын тулд дараах <a href="{{url}}">холбоос дээр дарна уу &raquo;</a></p>
{% endblock %}

webapps/root/templates/core/emailConfirmed.html
{% extends "core/registrationBorder.html" %}

{% block content %}
<p>Америк дахь Монгол Оюутны Холбоонд гишүүнээр элсэн орох өргөдөл явуулсан танд баярлалаа. Өргөдлийг тань бид түргэн хугацаанд хянан хариу өгөх болно. Хэрэв танд асуух зүйл байгаа бол amsa.amox@gmail.com хаягаар бидэнтэй холбогдоно уу.</p>

<p>Хүндэтгэсэн,</p>
<p>АМОХ Төлөөлөн Удирдах Зөвлөл.</p>
{% endblock %}

webapps/root/templates/core/index.html
{% extends "core/base.html" %}

{% block body %}
<div id="body">
<div class="jumbotron jumbotron-fluid background-img" id="hero-title-container" >

<div class="container">
  <h1 class="display-3" id="hero-title">Where Friendship Begins</h1>
  <p class="lead">"АМЕРИК ДАХЬ МОНГОЛ ОЮУТНЫ ХОЛБОО” төрийн бус байгууллагын зорилго нь дэлхий дахин дахь Монголын шилдэг оюутан, төгсөгчдийг хамарсан сүлжээ, тэдгээрийн мэдээллийн санг бий болгож, Монгол улс болон олон улсад боловсрол, эдийн засаг болон сайн санааны үйлс зохион байгуулж оролцоход оршино.
  </p>
  <form action="{% url 'core:registration' %}" method="get">
  <hr class="my-4">
  <p>Их сургуулийн и-мэйл хаяг</p>
  <div class="row">
    <div class="col-4 input-group">
      <input type="text" class="form-control form-control-lg right-text" name="schoolEmailPrefix" placeholder="@mycollege" aria-describedby="basic-addon2">
       <span class="input-group-addon" id="basic-addon2">.edu</span>
    </div>
    <div class="col-2">
       <input class="btn btn-primary btn-lg" type="submit" value="Эхэлцгээе">
    </div>
  </div>
  </form>
</div>
</div>
</div>
{% include "core/_footer.html" %} 
{% endblock %}

webapps/root/templates/core/pendingLetter.html
{% extends "core/emailLetterBase.html" %}
{% block body %}

<p>Эрхэм {{firstName}} танд энэ өдрийн мэндийг дэвшүүлэе.</p>

<p>Америк дахь Монгол Оюутны Холбоонд гишүүнээр элсэн орох өргөдөл явуулсан танд баярлалаа. Өргөдлийг тань бид түргэн хугацаанд хянан хариу өгөх болно. Хэрэв танд асуух зүйл байгаа бол amsa.amox@gmail.com хаягаар бидэнтэй холбогдоно уу.</p>

<p>Хүндэтгэсэн,</p>
<p>АМОХ Төлөөлөн Удирдах Зөвлөл.</p>
{% endblock %}

webapps/root/templates/core/registration.html
{% extends "core/registrationBorder.html" %}

{% block content %}
<h2 >Amsa Application Form</h1>
<p class="lead">Бүртгүүлэхийн тулд энэ маягтыг бөглөнө үү.</p>
<form action="{% url 'core:submitRegistration' %}" method="post">
  {% csrf_token %}
  <input type="hidden" name="schoolEmail" value="{{schoolEmail}}">
  <div class="container">
  	<div class="row">
      <div class="col-12">
        <div class="row top30"> <div class="col">Нэр </div></div>
        <div class="row top5">
          <div class="col-6">
            <input type="text" class="form-control" name="firstName" placeholder="Өөрийн" required/>
          </div>
          <div class="col-6">
            <input type="text" class="form-control" name="lastName" placeholder="Эцэг/эх нэр" required/>
          </div>
        </div>
        <div class="row top30"> <div class="col">Төрсөн өдөр </div></div>
        <div class="row top5">
            <div class="col-4">
              <select class="form-control" name="birthDay" required/>
              <option value="" disabled selected> Өдөр</option>
              {% for day in days %}
                <option value="{{day}}">{{day}}</option>
              {% endfor %}
              </select>
            </div>
            <div class="col-4">
              <select class="form-control" name="birthMonth" required/>
              <option value="" disabled selected>Сар</option>
              {% for month in months %}
                <option value="{{month}}">{{month}}</option>
              {% endfor %}
              </select>
            </div>
            <div class="col-4">
              <select class="form-control" name="birthYear" required/>
              <option value="" disabled selected>Жил</option>
              {% for year in possibleYearsToBorn %}
                <option value="{{year}}">{{year}}</option>
              {% endfor %}
              </select>
            </div>
        </div>
        <div class="row top30"> <div class="col">Хаяг</div></div>
        <div class="row top5">
          <div class="col-12">
            <input type="text" class="form-control" name="address1" placeholder="Хаяг 1 (123 Main Street)" required/>
          </div>
        </div>

        <div class="row top10">
          <div class="col-12">
            <input type="text" class="form-control" name="address2" placeholder="Хаяг 2 (Apt # 123)" />
          </div>
        </div>

        <div class="row top10">
          <div class="col-7">
            <input type="text" class="form-control" name="city" placeholder="Хот" required/>
          </div>
          <div class="col-3">
            {% include "core/stateSelectionDropdown.html" %}
          </div>
          <div class="col-2">
            <input type="text" class="form-control" name="zip" placeholder="Zip Код" required/>
          </div>
        </div>

        <div class="row top30"> <div class="col">Холбоо барих</div></div>
        <div class="row top10">
          <div class="col-6">
            <input type="text" class="form-control" name="phoneNumber" placeholder="Утасны дугаар" required/>
          </div>
          <div class="col-6">
            <input type="text" class="form-control" name="personalEmail" placeholder="Хувийн и-мэйл хаяг" required>
          </div>
        </div>

        <div class="row top30"> <div class="col">Сургуулийн тухай</div></div>
        <div class="row top15">
          <div class="col-8">
            <input type="text" class="form-control" name="schoolName" 
            placeholder="{%if not university%}Одоогийн хамрагдаж буй их сургууль (бүтнээр){%endif%}" {%if university%}value="{{university.school_name}}"{%endif%}  {%if university%}disabled{%endif%} required/>
          </div>
          <div class="col-4">
              <select class="form-control" name="graduationYear" required>
              <option value="" disabled selected>Төгсөх Жил</option>
              {% for year in possibleYearsToGraduate %}
                <option value="{{year}}">{{year}}</option>
              {% endfor %}
              </select>
          </div>
        </div>

        <div class="row top15">
          <div class="col-8">
            <input type="text" class="form-control" name="major" placeholder="Суралцаж буй мэргэжил" required/>
          </div>
          <div class="col-4">
              <select class="form-control" name="degreeLevel" required>
              <option value="" disabled selected>Горилж буй эрдмийн цол</option>
              {% for degreeLevel in degreeLevels %}
                <option value="{{degreeLevel.0}}">{{degreeLevel.1}}</option>
              {% endfor %}
              </select>
            </div>
        </div>

        <div class="row top15">
          <div class="col-12">
            <input type="text" class="form-control" name="secondMajor" placeholder="Давхар суралцаж буй мэргэжил (хэрвээ байгаа бол)"/>
          </div>
        </div>

        <div class="row top30"> <div class="col">Олон нийтийн сүлжээ</div></div>
        <div class="row top10">
          <div class="col-6">
            <input type="text" class="form-control" name="facebookLink" placeholder="Facebook link" required/>
          </div>
          <div class="col-6">
            <input type="text" class="form-control" name="linkedInLink" placeholder="LinkedIn link" />
          </div>
        </div>
        <div class="row top30"> 
          <div class="col"><input class="btn btn-primary btn-lg" type="submit" value="Бүртгүүлэх" /></div>
        </div>
      </div>
    </div>
  </div>
  
</form>

{% endblock %}

webapps/root/templates/core/registrationBorder.html
{% extends "core/base.html" %}

{% block body %}
<div id="body">
<div class="jumbotron jumbotron-fluid" id="registration-header">
  <div class="container">
  </div>
</div>
<div class="background-registration">
<div class="border-1 registrationBorder">
{% block content %}{% endblock %}
</div>
</div>
</div>
{% include "core/_footer.html" %} 
{% endblock %}

webapps/root/templates/core/rejectionLetter.html
{% extends "core/emailLetterBase.html" %}
{% block body %}
<p>Эрхэм {{firstName}} танд энэ өдрийн мэндийг дэвшүүлэе.</p>

<p>Америк дахь Монгол Оюутны Холбоонд гишүүнээр элсэн орох өргөдөл явуулсан таньд баярлалаа. Бид өргөдлийг тань хүлээн авсан боловч харамсалтай нь одоогийн байдлаар таныг элсүүлэх боломжгүй байгаад хүлцэл өчье. АМОХ бакалавр болон түүнээс дээш зэрэг эзэмших гэж суралцаж буй оюутнуудыг гишүүнээр элсүүлдэг дүрэмтэй юм. Хэрэв та дээрх нөхцөл байдлыг хангаж байгаа ч энэхүү email авсан бол бидэнтэй amsa.amox@gmail.com хаягаар холбогдоно уу. </p>

<p>АМОХ гишүүдээс гадна олон нийтэд нээлттэй үйл ажиллагаа явуулдаг тул биднийг <a href="https://www.facebook.com/oyutniikholboo/">Facebook хуудсаар</a> дагаж таны ойролцоо болох ирээдүйн уулзалт болон ярианд оролцохыг уриалж байна. Мөн та ирээдүйд Америкийн их сургуульд бакалавраас дээш зэрэгээр суралцвал, манай холбоонд гишүүнээр орно гэж найдаж байна. </p>

<p>Хүндэтгэсэн,</p>
<p>АМОХ Төлөөлөн Удирдах Зөвлөл.</p>
{% endblock %}

webapps/root/templates/core/submitRegistration.html
{% extends "core/registrationBorder.html" %}

{% block content %}
Та имэйлээ шалгана уу? Бид таны {{schoolEmail}} хаягруу тусгай линк явууллаа. Тус линкээр орж бүртгэлээ баталгаажуулна уу?
{% endblock %}